name: .NET CI/CD Pipeline

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build project
      run: dotnet build MicroservicesSolution.sln --configuration Release --no-restore

    - name: Publish to IIS
      run: dotnet publish OrderService/OrderService.csproj -c Release -o "D:\Deploy\MicroservicesSolution"
